name = "Island Optimized Deluxe Flavor"
author = "MoSadie"
version = "1.3.0"
description = "Optimization pack for MCCi with a few aesthetic additions."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c3912046d0bcad1dda41b869a8e4a901960012d5aaea9677f38e23d06d3746"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
