name = "Island Optimized Deluxe Flavor"
author = "MoSadie"
version = "1.4.1"
description = "Optimization pack for MCCi with a few aesthetic additions."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e6b0598486b81e10d04f0c993f83caa715b35f7ca1b602be3f4fb5546f3bd1"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
