name = "Island Optimized"
author = "MoSadie"
version = "1.0.0"
description = "Optimization pack for MCCi based on reccomendations by the Noxcrew."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d1d22cfbf109be6bd27dc5f24853b89a2d0c6984894f3983e8a9abea2784c1"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
