name = "Island Optimized Lite Flavor"
author = "MoSadie"
version = "1.3.0"
description = "Optimization pack for MCCi based on recommendations by the Noxcrew."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5a8efb7d55684a4f7da99b523ccef30e3519fdd066b61ebd650406a9102d18f"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
