name = "Island Optimized Lite Flavor"
author = "MoSadie"
version = "1.5.0"
description = "Optimization pack for MCCi based on recommendations by the Noxcrew."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4606043ba59aa73fdbc6828348676c4857059893e4c3e0265ffae649cd579f3d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
