name = "Island Optimized Lite Flavor"
author = "MoSadie"
version = "1.5.0"
description = "Optimization pack for MCCi based on recommendations by the Noxcrew."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d39d359c6cdb62f5dee524f25fd824b614440bf6f81b0ca74a7731baef23910"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
