name = "Island Optimized Creator Flavor"
author = "MoSadie"
version = "1.4.0"
description = "Optimization pack for MCCi with Replay Mod included."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40aa29fb7a4e495d4cb2e95e3a216354d52a50455e4b9c68712205f57acc5be0"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
