name = "Island Optimized Creator Flavor"
author = "MoSadie"
version = "1.2.0"
description = "Optimization pack for MCCi with Replay Mod included."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6bd238b1153876dcde896282b47923afacf8532435d8004e3ea2a022b60c271"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"
