name = "Island Optimized Creator Flavor"
author = "MoSadie"
version = "1.3.0"
description = "Optimization pack for MCCi with Replay Mod included."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9847724e6d9f388dacdd91b2c4eae3491810481e1483c869f88261e5615c66"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
